version: '3'
services:
  redis:
    image: redis:6.0.5
    command: redis-server --requirepass changeme --port 6379
    container_name: redis6379
    hostname: redis6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
  mysql:
    container_name: rd_db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "rd_db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Seoul'
    ports:
      - "3316:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"